server:
  port: 8888
  
spring:  application:    name: 'bikedot-config-server'  cloud:    config:      server:        git:          default-label: main
          uri: https://github.com/MichaelCX77/bikedot-config
          username: ${GITHUB_USER}
          password: ${GITHUB_PASS}