INSERT INTO CARRIER_TYPE (NAME , ACCESSIBILITY_ID ) VALUES ('LOJA', 1);
INSERT INTO CARRIER_TYPE (NAME , ACCESSIBILITY_ID ) VALUES ('LOJA', 4);
INSERT INTO CARRIER_TYPE (NAME , ACCESSIBILITY_ID ) VALUES ('EMPRESA', 3);
INSERT INTO CARRIER_TYPE (NAME , ACCESSIBILITY_ID ) VALUES ('PRAÇA', 1);
INSERT INTO CARRIER_TYPE (NAME , ACCESSIBILITY_ID ) VALUES ('PRACA', 2);
INSERT INTO CARRIER_TYPE (NAME , ACCESSIBILITY_ID ) VALUES ('UNIVERSIDADE', 3);