INSERT INTO CARRIER (DESCRIPTION , TYPE_ID , REFRENCE ) VALUES ('EXTRA', 1, 'Próximo à entrada');
INSERT INTO CARRIER (DESCRIPTION , TYPE_ID , REFRENCE ) VALUES ('PARQUE IBIRAPUERA', 2, 'Estacionamento - Entrada 4');
INSERT INTO CARRIER (DESCRIPTION , TYPE_ID , REFRENCE ) VALUES ('USP', 6, 'Estacionamento 2');
INSERT INTO CARRIER (DESCRIPTION , TYPE_ID , REFRENCE ) VALUES ('CALÇADA', 1, 'Próximo à padaria');
INSERT INTO CARRIER (DESCRIPTION , TYPE_ID , REFRENCE ) VALUES ('BEDUINO RESTAURANTE', 4, 'Estacionamento traseiro');